site_name: SNPsplit
repo_name: FelixKrueger/SNPsplit
repo_url: https://github.com/FelixKrueger/SNPsplit
site_url: https://felixkrueger.github.io/SNPsplit
edit_uri: edit/master/docs/

theme:
  name: material
  logo: images/SNPsplit.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Noto Sans
  features:
    - navigation.instant
    - navigation.tabs

nav:
  - Overview: README.md
  - workflow.md
  - Genome preparation:
      - genome_prep/README.md
      - genome_prep/genome_preparation.md
      - bismark/alignment.md
      - bismark/deduplication.md
      - bismark/methylation_extraction.md
      - bismark/coverage_report.md
      - bismark/processing_report.md
      - bismark/summary_report.md
      - bismark/filter_nonconverted_reads.md
      - bismark/library_types.md
  - SNPsplit:
      - SNPsplit/README.md
      - SNPsplit/genome_preparation.md
  - Full list of options:
      - options/genome_preparation.md
      - options/alignment.md
      - options/methylation_extraction.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
plugins:
  - social
  - search
