#!/usr/bin/perl
use warnings;
use strict;
use Getopt::Long;
use FindBin qw($Bin);
use lib "$Bin/../lib";
use Cwd;

## This program is Copyright (C) 2014-16, Felix Krueger (felix.krueger@babraham.ac.uk)

## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.

## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.

## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.


### This script filters the latest VCF file for various SNPs versus the GRCm38 mouse genome build and writes high confidence SNPs into a folder called 'SNPs_Sanger';
### It has been tested with the latest version of the SNP file 'mgp.v5.merged.snps_all.dbSNP142.vcf.gz' at the time of writing (20 Jan 2016). I can't guarantee that
### it will work with any other supplied VCF file.

## Reading in a BAM or SAM file
my $pipeline_version = '0.3.devel';
my $parent_dir = getcwd();
my ($vcf_file,$ucsc,$strain,$genome_folder) = process_commandline ();

warn "Summarising SNPsplit Genome Preparation Parameters\n";
warn "="x50,"\n";
warn "Processing SNPs from VCF file:\t\t $vcf_file\n";
warn "Reference genome:\t\t\t$genome_folder\n";
warn "\n";

### Dealing with chromosomes
my @chroms = detect_chroms();
print "Using the following chromosomes (detected from VCF file >>$vcf_file<<):\n";
print join ("\t",@chroms),"\n\n";

### Dealing with strains
my $strain_index;
deal_with_strains();

### Determining and Filtering homozygous high-confidence SNPs for the strain in question
# filter_relevant_SNP_calls_from_VCF();
warn "Finished filtering and writing out SNPs\n\n";

my %chromosomes; # Storing the genomic sequence
read_genome_into_memory($parent_dir);

sub read_genome_into_memory{
    
    ## working directoy
    my $cwd = shift;
    
    ## reading in and storing the specified genome in the %chromosomes hash
    chdir ($genome_folder) or die "Can't move to $genome_folder: $!";
    warn "Now reading in and storing sequence information of the genome specified in: $genome_folder\n\n";

    my @chromosome_filenames =  <*.fa>;

    ### if there aren't any genomic files with the extension .fa we will look for files with the extension .fasta
    unless (@chromosome_filenames){
      @chromosome_filenames =  <*.fasta>;
    }

    unless (@chromosome_filenames){
      die "The specified genome folder $genome_folder does not contain any sequence files in FastA format (with .fa or .fasta file extensions)\n";
    }

    my $SQ_count = 0;

    foreach my $chromosome_filename (@chromosome_filenames){

	open (CHR_IN,$chromosome_filename) or die "Failed to read from sequence file $chromosome_filename $!\n";
	### first line needs to be a fastA header
	my $first_line = <CHR_IN>;
	chomp $first_line;
	$first_line =~ s/\r//;
	### Extracting chromosome name from the FastA header
	my $chromosome_name = extract_chromosome_name($first_line);
	my $sequence;

	while (<CHR_IN>){
	  chomp;
	  $_ =~ s/\r//; # removing carriage returns if present
	  if ($_ =~ /^>/){
	
	    ### storing the previous chromosome in the %chromosomes hash, only relevant for Multi-Fasta-Files (MFA)
	    if (exists $chromosomes{$chromosome_name}){
	      print "chr $chromosome_name (",length $sequence ," bp)\n";
	      die "Exiting because chromosome name already exists. Please make sure all chromosomes have a unique name!\n";
	    }
	    else {
	      if (length($sequence) == 0){
		warn "Chromosome $chromosome_name in the multi-fasta file $chromosome_filename did not contain any sequence information!\n";
	      }
	      print "chr $chromosome_name (",length $sequence ," bp)\n";
	      $chromosomes{$chromosome_name} = $sequence;
	    }
	    ### resetting the sequence variable
	    $sequence = '';
	    ### setting new chromosome name
	    $chromosome_name = extract_chromosome_name($_);
	  }
	  else{
	    $sequence .= uc$_;
	  }
	}
	
 	### Processing last chromosome of a multi Fasta File or the only entry in case of single entry FastA files

	if (exists $chromosomes{$chromosome_name}){
	    print "chr $chromosome_name (",length $sequence ," bp)\t";
	    die "Exiting because chromosome name already exists. Please make sure all chromosomes have a unique name.\n";
	}
	else{
	    if (length($sequence) == 0){
		warn "Chromosome $chromosome_name in the file $chromosome_filename did not contain any sequence information!\n";
	    }

	    print "chr $chromosome_name (",length $sequence ," bp)\n";
	    $chromosomes{$chromosome_name} = $sequence;
	}
    }
    print "\n";
    chdir $cwd or die "Failed to move to directory $cwd\n";

}
sub extract_chromosome_name {
    ## Bowtie seems to extract the first string after the inition > in the FASTA file, so we are doing this as well
    my $fasta_header = shift;
    if ($fasta_header =~ s/^>//){
	my ($chromosome_name) = split (/\s+/,$fasta_header);
	return $chromosome_name;
    }
    else{
	die "The specified chromosome ($fasta_header) file doesn't seem to be in FASTA format as required!\n";
    }
}

###


sub filter_relevant_SNP_calls_from_VCF{
    
    if ($vcf_file =~ /gz$/){
	open (IN,"gunzip -c $vcf_file |") or die "Failed to open file '$vcf_file': $!\n";
    } 
    else{
	open (IN, $vcf_file) or die "Failed to read Input VCF file '$vcf_file': $!\n";
    }
    
    my $count = 0;

    my $other = 0;
    my $too_many = 0;
    
    my %fhs;
    my $hcg_count = 0;
    my $low_confidence = 0;
    my $same = 0;
    my $homozygous = 0;
    my %all_SNPs;
    

  
    my $dir = "SNPs_$strain";
    unless (-d $dir){
	warn "Folder '$dir' doesn't exist. Creating it for you...\n\n";
	mkdir $dir or die "Failed to created directory $dir\n: $!\n\n";
    }
    
    # Opening filehandles for the SNP files
    for my $chr (@chroms) {
	my $filename = "SNPs_$strain/chr".$chr.'.txt';
	open (my $fh,'>',$filename) or die "Couldn't open filehandle $!\n";
	$fhs{$chr} = $fh;
	print {$fhs{$chr}} ">$chr\n";
    }
    
    while (<IN>){
	$_ =~ s/(\r|\n)//g; # removing end of line characters

	# warn "$_\n"; sleep(1);
	next if ($_ =~ /^\#\#/); # filters out header information lines
	if ($_ =~ /^\#CHROM/){ # Table Header
	    my ($name) = (split /\t/)[$strain_index];
	    warn "Analysing SNP fields for name >$name<\n";
	    next;	
	}
	$count++;
	if ($count%1000000 ==0){
	    warn "processed $count lines\n";
	}
	# last if ($count == 1000);
	
	my ($chr,$pos,$ref,$alt,$strain) = (split /\t/)[0,1,3,4,$strain_index];
	# warn "$chr , $pos , $ref , $alt , $strain\n"; sleep(1);
	
	# $strain is in the form: GT:GQ:DP:MQ0F:GP:PL:AN:MQ:DV:DP4:SP:SGB:PV4:FI
	my ($gt,$gq,$dp,$mq0f,$gp,$pl,$an,$mq,$dv,$dp4,$sp,$sgb,$pv4,$fi) = split/:/,$strain;
	
	
	unless ($fi){
	    # warn "genotype: $gt\nfilter:   $fi\n\n";
	}

	# warn "genotype: $gt\nfilter:   $fi\n\n";
	# warn "$fi\n"; sleep(1);
	# $gt is the Genotype:
	
	# '.'   = no genotype call was made
	# '0/0' = genotype is the same as the reference genome
	# '1/1' = homozygous alternative allele; can also be '2/2',
	# '3/3', etc. if more than one alternative allele is present.
	# '0/1' = heterozygous genotype; can also be '1/2', '0/2', etc.
	
	# $fi is filter, 1 for high confidence SNP, or 0 for low confidence
	
	### We are only looking for 1/1 calls, and filter for high confidence as well
	
	# skipping if the reference base is not well defined in Black6
	if ($ref =~ /[^ATCG]/){ # reference base contained any non A, C, T, G characters or more than one base
	    warn "ref was: $ref; skipping\n";
	    next;
	}
	
	# skipping if the SNP is not well defined in the strain of interest
	if ($alt =~ /[^ATCG]/){ # Alt base contained any non A, C, T, G characters or more than one base
	    # warn "SNP was: $alt; skipping\n";
	    ++$too_many;
	    next;
	}
	
	# Filtering for genotype
	if ($gt eq '0/0'){
	    ++$same;
	    # warn "same as reference\n";
	    next;
	}
	elsif ($gt eq '1/1'){
	    ++$homozygous;
	    # warn "homozygous alternative allele\n";
	}
	else{
	    ++$other;
	    next;
	}
	
	# Looking at the Filtering tag
	# warn "$fi\n"; sleep(1);
	if ($fi == 1){
	    ++$hcg_count;
	    
	    my $location = join (':',$chr,$pos);
	    # warn "$location\n";
	    my $SNP = join ("\t",$count,$chr,$pos,'1',join ("\/",$ref,$alt));
	    # field 4: 1 means top strand, -1 means reverse strand
	    # warn "$SNP\n";sleep(1);
	    
	    if (exists $all_SNPs{$location} ){
		# warn "SNP $all_SNPs{$location} position was present already\n";
	    }
	    else{
		$all_SNPs{$location} = $SNP;
	    }
	}
	else{
	    ++$low_confidence;
	    next;
	}
	
	# Output example
	# Variation ID    Chromosome name Position on Chromosome (bp)     Strand  Allele
	# rs2020560       10      98212004        1       A/T
	
	print {$fhs{$chr}} join ("\t",$count,$chr,$pos,'1',join ("\/",$ref,$alt),$strain),"\n";
	
    }
    
    # Writing a report file
    my $report = "${strain}_genome_preparation_report.txt";
    open (REPORT,'>',$report) or die "Failed to write to file $report: $!\n";
    
    warn "SNP position summary for strain $strain (based on mouse genome build GRCm38)\n";
    warn "="x80,"\n\n";
    warn "Positions read in total:\t$count\n\n";
    warn "$homozygous\tSNP were homozygous. Of these:\n";
    warn "$hcg_count\tSNP were homozygous and passed high confidence filters and were thus included into the $strain genome\n";
    warn "\nNot included into $strain genome:\n";
    warn "$same\thad the same sequence as the reference\n";
    warn "$too_many\t\thad no clearly defined alternative base\n";
    warn "$other\t\tCalls were neither 0/0 (same as reference) or 1/1 (homozygous SNP)\n";
    warn "$low_confidence\t\twere homozygous but the filtering call was low confidence\n\n";

    print REPORT "SNP position summary for strain $strain (based on mouse genome build GRCm38)\n";
    print REPORT "="x80,"\n\n";
    print REPORT "Positions read in total:\t$count\n\n";
    print REPORT "$homozygous\tSNP were homozygous. Of these:\n";
    print REPORT "$hcg_count\tSNP were homozygous and passed high confidence filters and were thus included into the $strain genome\n";
    print REPORT "\nNot included into $strain genome:\n";
    print REPORT "$same\thad the same sequence as the reference\n";
    print REPORT "$too_many\t\thad no clearly defined alternative base\n";
    print REPORT "$other\t\tCalls were neither 0/0 (same as reference) or 1/1 (homozygous SNP)\n";
    print REPORT "$low_confidence\t\twere homozygous but the filtering call was low confidence\n\n";
    
    # Also writing all SNP calls out to an all-SNP file
    warn "Now printing a single list of all SNPs\n\n";
    my $all_SNPs = "all_SNPs_${strain}_GRCm38.txt.gz";
    if (-e $all_SNPs){
	warn "File '$all_SNPs' existed in the folder already, overwriting it...\n\n";
    }
    open (ALLSNP,"| gzip -c - > $all_SNPs") or die "Failed to write to file $all_SNPs: $!\n";
    
    foreach my $location (keys %all_SNPs){
	print ALLSNP "$all_SNPs{$location}\n";
    }
        
}

### SUBROUTINES

sub deal_with_strains{
    # Dealing with strains
    my %strains = detect_strains($vcf_file); # getting a list of strains to choose from before exiting
    
    if (defined $strain){
	if (exists $strains{$strain}){
	    $strain_index = $strains{$strain};
	    warn "Strain defined as '$strain' (strain index: $strain_index)\n";
	}
	else{
	    warn "Strain name specified ($strain) does not match any of the available strain names!\n";
	    warn "\nAvailable genomes to choose from are:\n";
	    warn "="x37,"\n";	
	    foreach my $strain(keys %strains){
		print "$strain\n";
	    }
	    warn "="x37,"\n";
	    die "\nPlease double check the name and try again (using '--strain NAME')\n\n";
	}
    }
    else{
	warn "No strain specified!\n";
	warn "\nAvailable genomes to choose from are:\n";
	warn "="x37,"\n";	
	foreach my $strain(keys %strains){
	    print "$strain\n";
	}
	warn "="x37,"\n";
	die "\nPlease choose one of the available strains using '--strain NAME' and try again\n\n";
    }
}


sub detect_chroms{

    my %chrom; # detecting the chromosomes from the VCF file
    my @chrom;

    if ($vcf_file =~ /gz$/){
	open (DETECT,"gunzip -c $vcf_file |") or die "Failed to open file '$vcf_file': $!\n";
    }
    else{
	open (DETECT, $vcf_file) or die "Failed to read Input VCF file '$vcf_file': $!\n";
    }
    
    # warn "Detecting chromosomes from file '$vcf_file'\n\n";
    while (<DETECT>){
	$_ =~ s/(\r|\n)//g; # removing end of line characters
	last unless ($_ =~ /^\#/);
	
	if ($_ =~ /^\#\#contig/){ # filters header lines
	    # warn "$_\n"; # sleep(1);
	    $_ =~ /ID=(.+),/;
	    my $chr = $1;
	    # warn "Identified chromosome $chr\n";
	    unless (exists $chrom{$chr}){
		$chrom{$chr}++;
	    }
	}
    }

    foreach my $chr(keys %chrom){
	# warn "$chr\n";	
	push @chrom, $chr;
    }
    # close DETECT or warn "Failed to close filehandle DETECT: $!\n";
    return @chrom;
    
}

sub detect_strains{
    
    my $vcf_file = shift;
    my %strains; # detecting the available strains from the VCF file
    
    if ($vcf_file =~ /gz$/){
	open (STRAIN,"gunzip -c $vcf_file |") or die "Failed to open file '$vcf_file': $!\n";
    }
    else{
	open (STRAIN, $vcf_file) or die "Failed to read Input VCF file '$vcf_file': $!\n";
    }
    
    # warn "Detecting strains from file '$vcf_file'\n\n";
    while (<STRAIN>){
	$_ =~ s/(\r|\n)//g; # removing end of line characters
	next if ($_ =~ /^\#\#/);	
	if ($_ =~ /^\#CHROM/){ # header line listing all different strains
	    # warn "$_\n"; sleep(1);
	}
	last unless ($_ =~ /^\#/); # everything from now on are the SNPs themselves
	
	my @strains = split (/\t/);
	
	foreach my $index(0..$#strains){
	    next if ($index <= 8); # The first 6 fields are irrelevant: #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  
	    $strains{$strains[$index]} = $index; 
	    # warn "$index\t$strains[$index]\n";
	}
    }
    
    # close STRAIN or warn "Failed to close filehandle STRAIN: $!\n";
    return %strains;

}



sub process_commandline{
    my $help;
    my $version;
    my $vcf_file;
    my $strain;
    my $list_strains;
    my $genome_folder;
    
    my $command_line = GetOptions ('help|man'             => \$help,
				   'versions'             => \$version,
				   'strain=s'             => \$strain,
				   'list_strains'         => \$list_strains,
				   'vcf_file=s'           => \$vcf_file,
				   'genome_folder=s'      => \$genome_folder,
	);
  
  ### EXIT ON ERROR if there were errors with any of the supplied options
  unless ($command_line){
      die "Please respecify command line options\n";
  }

  ### HELPFILE
  if ($help){
      print_helpfile();
      exit;
  }

  if ($version){
      print << "VERSION";

                               SNPsplit Genome Preparation
                                   version: $pipeline_version
                 Copyright 2014-16 Felix Krueger, Babraham Bioinformatics


VERSION
    exit;
  }

    if (defined $vcf_file){
	unless(-e $vcf_file){
	    die "Input VCF file '$vcf_file' doesn't exist in the folder. Please check filenames and try again!\n\n";
	}
    }
    else{
	die "\nYou need to provide a VCF file detailing SNPs positions with '--vcf_file your.file' (e.g.: --vcf mgp.v5.merged.snps_all.dbSNP142.vcf.gz). Please respecify!\n\n";
    }
    
    if ($list_strains){
	warn "\nAvailable genomes to choose from are:\n";
	warn "="x37,"\n";
	my %strains = detect_strains($vcf_file);
	foreach my $strain(keys %strains){
	    print "$strain\n";
	}
	warn "="x37,"\n";
	warn "\nPlease choose one using '--strain NAME'\n\n";
	exit;
    }
    
    ### GENOME FOLDER
    
    unless ($genome_folder){
	warn "Genome folder was not specified!\n";
	# print_helpfile();
	exit;
    }
    my $parent_dir = getcwd();    

    ### checking that the genome folder, all subfolders and the required bowtie index files exist
    unless ($genome_folder =~/\/$/){
	$genome_folder =~ s/$/\//;
    }
    
    if (chdir $genome_folder){
	my $absolute_genome_folder = getcwd; ## making the genome folder path absolute
	unless ($absolute_genome_folder =~/\/$/){
	    $absolute_genome_folder =~ s/$/\//;
	}
	warn "Reference genome folder provided is $genome_folder\t(absolute path is '$absolute_genome_folder)'\n\n";
	$genome_folder = $absolute_genome_folder;
    }
    else{
	die "Failed to move to $genome_folder: $!\n\nSNPsplit_genome_preparation --help for more details\n\n";
    }
    chdir $parent_dir or die "Failed to move back to parent directory $parent_dir\n\n";
    
    return ($vcf_file,$ucsc,$strain,$genome_folder);

}


## Last modified on 28 April 2016
